### PR TITLE
Add support for StatsD tags

### PR DESCRIPTION
**Pull request by TheConnMan**
Add support for optional tags for use when sending data into services like Netuitive.

### CODE REVIEW

**Comment by TheConnMan** [comment]
Addresses part of #56

**Comment by papandreou** [comment]
Interesting, I wasn't aware of that statsd feature. Seems like https://www.npmjs.com/package/node-statsd also supports it. LGTM!

**Comment by msiebuhr** [comment]
Released as `v0.3.0`

**Comment by Chris911** [comment]
Is there a reason this was added only for global tags and not per metrics tags? Both node-statsd and node-dogstatsd support per metric tag which seems more useful than global tags. If you're open to the happy I'll gladly submit a PR.

**Comment by msiebuhr** [comment]
No good reason. If you can whip up a PR, we'll do it.

**Comment by Chris911** [comment]
Follow up PR: https://github.com/msiebuhr/node-statsd-client/pull/73

**Pull request merged**
